export const getSxClasses = () => ({
  wrapper: { width: '100%' },
  title: { fontWeight: 600, mb: 2 },
  carousel: {
    position: 'relative',
    width: '100%',
    aspectRatio: '16 / 9',
    borderRadius: 2,
    overflow: 'hidden',
    backgroundColor: 'grey.900',
    outline: 'none',
  },
  image: (objectFit: 'cover' | 'contain' | 'fill' | 'none' | 'scale-down') => ({
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    objectFit,
  }),
  expandButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    color: 'common.white',
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    '&:hover': { backgroundColor: 'rgba(0, 0, 0, 0.55)' },
  },
  // Positioned on whichever side leaves the important part of the photo uncovered
  textOverlay: (position: 'left' | 'right') => ({
    position: 'absolute',
    top: 0,
    bottom: 0,
    [position]: 0,
    width: { xs: '100%', sm: '42%' },
    display: 'flex',
    alignItems: 'center',
    p: { xs: 2, sm: 3 },
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
  }),
  overlayText: {
    color: 'common.white',
    lineHeight: 1.6,
  },
  navButton: (side: 'left' | 'right') => ({
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
    [side]: 8,
    color: 'common.white',
    backgroundColor: 'transparent',
    '&:hover': { backgroundColor: 'rgba(0, 0, 0, 0.4)' },
    '&.Mui-disabled': { color: 'rgba(255, 255, 255, 0.3)' },
  }),
  dots: {
    position: 'absolute',
    bottom: 12,
    left: '50%',
    transform: 'translateX(-50%)',
    display: 'flex',
    gap: 1,
  },
  dot: (isActive: boolean) => ({
    width: isActive ? 10 : 8,
    height: isActive ? 10 : 8,
    borderRadius: '50%',
    border: 'none',
    padding: 0,
    cursor: 'pointer',
    backgroundColor: isActive ? 'common.white' : 'rgba(255, 255, 255, 0.5)',
    transition: 'all 0.2s ease',
    '&:hover': { backgroundColor: 'common.white' },
  }),
  visuallyHidden: {
    position: 'absolute',
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: 'hidden',
    clip: 'rect(0, 0, 0, 0)',
    whiteSpace: 'nowrap',
    border: 0,
  },
  lightboxModal: { display: 'flex' },
  lightboxBackdrop: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
    outline: 'none',
  },
  lightboxCloseButton: {
    position: 'absolute',
    top: 16,
    right: 16,
    color: 'common.white',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    '&:hover': { backgroundColor: 'rgba(0, 0, 0, 0.7)' },
  },
  lightboxImage: {
    display: 'block',
    maxWidth: '90vw',
    maxHeight: '90vh',
    width: 'auto',
    height: 'auto',
    // Always shows the whole image uncropped, regardless of the carousel's own objectFit setting
    objectFit: 'contain',
  },
});
